version: '3.1'

services:

  flask_celery:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - my_network

  celery_worker:
    build:
      context: .
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network


networks:
  my_network: